apiVersion: v1
kind: Pod
metadata:
  name: b-3
  labels:
    user: B
spec:
  schedulerName: drf-scheduler
  restartPolicy: Never
  containers:
    - name: main
      image: registry.k8s.io/pause:3.9
      resources:
        requests:
          cpu: "500m"
          memory: "1Gi"
        limits:
          cpu: "500m"
          memory: "1Gi"

