apiVersion: v1
kind: Pod
metadata:
  name: pod-a-1
  labels:
    user: a
spec:
  schedulerName: drf-scheduler
  restartPolicy: Never
  containers:
    - name: main
      image: registry.k8s.io/pause:3.9
      resources:
        requests:
          cpu: "900m"
          memory: "128Mi"
        limits:
          cpu: "900m"
          memory: "128Mi"