apiVersion: v1
kind: Pod
metadata:
  name: pod-b-1
  labels:
    user: b
spec:
  schedulerName: drf-scheduler
  restartPolicy: Never
  containers:
    - name: main
      image: registry.k8s.io/pause:3.9
      resources:
        requests:
          cpu: "200m"
          memory: "768Mi"
        limits:
          cpu: "200m"
          memory: "768Mi"